/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Juros.java
 *
 * Created on Feb 14, 2010, 10:30:02 PM
 */

package br.org.auxiliar.grana.ui.matisse;

import br.org.auxiliar.grana.core.financial.Rule72;

/**
 *
 * @author fabio
 */
public class Juros extends javax.swing.JInternalFrame {

    /** Creates new form Juros */
    public Juros() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTabbedPane1 = new javax.swing.JTabbedPane();
    Rule72 = new javax.swing.JPanel();
    labelAliquota = new javax.swing.JLabel();
    aliquota = new javax.swing.JFormattedTextField();
    grpResultado = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    btnCalcular = new javax.swing.JButton();
    Fechar = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();

    setClosable(true);
    setTitle("Juros");

    labelAliquota.setLabelFor(aliquota);
    labelAliquota.setText("Aliquota ( % )");

    jLabel1.setText("jLabel1");

    javax.swing.GroupLayout grpResultadoLayout = new javax.swing.GroupLayout(grpResultado);
    grpResultado.setLayout(grpResultadoLayout);
    grpResultadoLayout.setHorizontalGroup(
      grpResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(grpResultadoLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addContainerGap(37, Short.MAX_VALUE))
    );
    grpResultadoLayout.setVerticalGroup(
      grpResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(grpResultadoLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addContainerGap(73, Short.MAX_VALUE))
    );

    btnCalcular.setMnemonic('c');
    btnCalcular.setText("Calcular");
    btnCalcular.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCalcularActionPerformed(evt);
      }
    });

    Fechar.setMnemonic('f');
    Fechar.setText("Fechar");

    javax.swing.GroupLayout Rule72Layout = new javax.swing.GroupLayout(Rule72);
    Rule72.setLayout(Rule72Layout);
    Rule72Layout.setHorizontalGroup(
      Rule72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(Rule72Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(Rule72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelAliquota)
          .addGroup(Rule72Layout.createSequentialGroup()
            .addComponent(btnCalcular)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Fechar))
          .addComponent(aliquota, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(grpResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(19, Short.MAX_VALUE))
    );
    Rule72Layout.setVerticalGroup(
      Rule72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(Rule72Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(Rule72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(grpResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(Rule72Layout.createSequentialGroup()
            .addComponent(labelAliquota)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(aliquota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(Rule72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(btnCalcular)
              .addComponent(Fechar))))
        .addGap(135, 135, 135))
    );

    jTabbedPane1.addTab("Regra 72", Rule72);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 331, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 124, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("tab2", jPanel2);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
      rule72 = new Rule72(aliquota.getText());
      jLabel1.setText(rule72.getResultInMonth());
    }//GEN-LAST:event_btnCalcularActionPerformed
private Rule72 rule72;

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton Fechar;
  private javax.swing.JPanel Rule72;
  private javax.swing.JFormattedTextField aliquota;
  private javax.swing.JButton btnCalcular;
  private javax.swing.JPanel grpResultado;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JTabbedPane jTabbedPane1;
  private javax.swing.JLabel labelAliquota;
  // End of variables declaration//GEN-END:variables

}
